#spring:
#  datasource:
#    url: jdbc:mariadb:// 127.0.0.1:3306/library
#    hikari:
#      username: admin
#      password: changeme
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        hbm2ddl:
#          auto: update
#        dialect: org.hibernate.dialect.MariaDBDialect
#    open-in-view: false

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//im2ag-oracle.univ-grenoble-alpes.fr:1521/im2ag
    username: jandotdf
    password: 8bb1d6b3c4
    hikari:
      maximum-pool-size: 20
      schema: jandotdf
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: true